# Generated by Django 5.2.12 on 2026-09-02 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentRead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("daily_ca_article", "Daily CA Article"),
                            ("concept", "Concept"),
                            ("article", "Generated Article"),
                        ],
                        help_text="Which kind of content was read",
                        max_length=32,
                    ),
                ),
                (
                    "content_id",
                    models.CharField(
                        help_text="Slug or UUID as text. Intentionally not a ForeignKey — see the class docstring",
                        max_length=255,
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        help_text="Salted SHA-256 of the client IP, used only for daily dedupe",
                        max_length=64,
                    ),
                ),
                (
                    "is_authenticated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the reader was signed in. Boolean only, no user FK",
                    ),
                ),
                (
                    "read_date",
                    models.DateField(
                        help_text="Local date of the read. Stored explicitly so the unique constraint below can collapse repeat reads to one row per day"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the beacon fired"
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Read",
                "verbose_name_plural": "Content Reads",
                "db_table": "telemetry_content_read",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "content_id", "-read_date"],
                        name="telemetry_c_content_460125_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="telemetry_c_created_70dc65_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "content_id", "ip_hash", "read_date"),
                        name="uniq_content_read_per_visitor_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VisitLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Request path, truncated to the column width",
                        max_length=512,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="HTTP method (GET, POST, ...)", max_length=10
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        help_text="Response status — makes error-path analysis possible"
                    ),
                ),
                (
                    "referrer",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referer header if present, truncated. Empty string, never NULL",
                        max_length=512,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User-Agent header, truncated. Empty string, never NULL",
                        max_length=512,
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        help_text="Salted SHA-256 of the client IP. The raw IP is NEVER stored, logged or sent to Sentry. Salt comes from TELEMETRY_IP_SALT — an unsalted hash of an IPv4 address is trivially reversible, since the whole address space enumerates in seconds",
                        max_length=64,
                    ),
                ),
                (
                    "is_authenticated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the request was signed in. Boolean only — there is no user FK on this model, so a row can never identify a person",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the request was served"
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit Log",
                "verbose_name_plural": "Visit Logs",
                "db_table": "telemetry_visit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="telemetry_v_created_84c606_idx"
                    ),
                    models.Index(
                        fields=["path", "-created_at"],
                        name="telemetry_v_path_628f8a_idx",
                    ),
                    models.Index(
                        fields=["status_code", "-created_at"],
                        name="telemetry_v_status__e8b0e9_idx",
                    ),
                ],
            },
        ),
    ]
