# Generated by Django 5.2.12 on 2026-09-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0002_contentread_topic_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentread",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("daily_ca_article", "Daily CA Article"),
                    ("concept", "Concept"),
                    ("article", "Generated Article"),
                    ("topic", "Knowledge Map Topic"),
                    ("current_affairs", "Current Affairs Item"),
                ],
                help_text="Which kind of content was read",
                max_length=32,
            ),
        ),
    ]
