# Generated by Django 5.0.14 on 2026-02-05 10:18

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import pgvector.django.vector
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the document",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title (e.g., 'NCERT Class 12 Polity')",
                        max_length=500,
                    ),
                ),
                (
                    "file_path",
                    models.TextField(
                        help_text="Storage path or URL to the original file"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("static", "Static Content (NCERT, Books)"),
                            ("dynamic", "Dynamic Content (Web, News)"),
                        ],
                        help_text="Content category for retrieval strategy",
                        max_length=50,
                    ),
                ),
                (
                    "source_edition",
                    models.CharField(
                        blank=True,
                        help_text="Edition identifier (e.g., 'NCERT 2024', 'Laxmikanth 6th Ed')",
                        max_length=50,
                    ),
                ),
                (
                    "source_version",
                    models.CharField(
                        blank=True,
                        help_text="Version number (e.g., '1.0', '2.1')",
                        max_length=20,
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True, help_text="ISBN for books", max_length=20
                    ),
                ),
                (
                    "publication_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Year of publication",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (author, publisher, tags, etc.)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Document upload timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "content_document",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_type"], name="content_doc_source__925a6e_idx"
                    ),
                    models.Index(
                        fields=["source_edition"], name="content_doc_source__e5f735_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="content_doc_created_c540c9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the chunk",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chunk_text",
                    models.TextField(
                        help_text="The actual text content of the chunk (~1200 characters)"
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="Sequential index within the document (0, 1, 2...)"
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True, help_text="Source page number (for PDFs)", null=True
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("static", "Static Content"),
                            ("dynamic", "Dynamic Content (Current Affairs)"),
                        ],
                        help_text="Matches parent document's source_type for efficient filtering",
                        max_length=50,
                    ),
                ),
                (
                    "chapter_name",
                    models.CharField(
                        blank=True,
                        help_text="Chapter/section name extracted from document structure",
                        max_length=200,
                    ),
                ),
                (
                    "quality_flag",
                    models.CharField(
                        choices=[
                            ("high", "High Quality"),
                            ("medium", "Medium Quality"),
                            ("low", "Low Quality"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="high",
                        help_text="Quality assessment of chunk extraction",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=1.0,
                        help_text="OCR or extraction confidence (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Chunk creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Parent document this chunk belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="content.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk",
                "verbose_name_plural": "Chunks",
                "db_table": "content_chunk",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the embedding",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("chunk", "Chunk Embedding"),
                            ("article", "Article Embedding (future)"),
                            ("question", "Question Embedding (future)"),
                        ],
                        help_text="Type of content being embedded",
                        max_length=50,
                    ),
                ),
                (
                    "content_id",
                    models.UUIDField(
                        help_text="UUID of the content (chunk_id, article_id, etc.)"
                    ),
                ),
                (
                    "vector",
                    pgvector.django.vector.VectorField(
                        dimensions=384, help_text="384-dimensional embedding vector"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="all-MiniLM-L6-v2",
                        help_text="Embedding model used for generation",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Embedding generation timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding",
                "verbose_name_plural": "Embeddings",
                "db_table": "content_embedding",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="content_emb_content_bf58a9_idx",
                    )
                ],
                "unique_together": {("content_type", "content_id")},
            },
        ),
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the ingestion job",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current job status",
                        max_length=20,
                    ),
                ),
                (
                    "error_log",
                    models.TextField(
                        blank=True, help_text="Error messages if job failed"
                    ),
                ),
                (
                    "total_pages",
                    models.IntegerField(
                        blank=True,
                        help_text="Total pages in document (for progress calculation)",
                        null=True,
                    ),
                ),
                (
                    "processed_pages",
                    models.IntegerField(default=0, help_text="Pages processed so far"),
                ),
                (
                    "chunks_created",
                    models.IntegerField(
                        default=0, help_text="Number of chunks created"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="Job start timestamp", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Job completion timestamp", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Job creation timestamp"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Document being processed (null if job failed before document creation)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_jobs",
                        to="content.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingestion Job",
                "verbose_name_plural": "Ingestion Jobs",
                "db_table": "content_ingestion_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the asset",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("table", "Table"),
                            ("diagram", "Diagram/Image"),
                            ("formula", "Mathematical Formula"),
                        ],
                        help_text="Type of extracted asset",
                        max_length=50,
                    ),
                ),
                (
                    "asset_url",
                    models.TextField(
                        blank=True, help_text="CDN URL or file path to the asset"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Asset-specific metadata (dimensions, format, etc.)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Asset extraction timestamp"
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        help_text="Parent chunk this asset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="content.chunk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "content_asset",
                "ordering": ["chunk", "asset_type"],
                "indexes": [
                    models.Index(
                        fields=["chunk"], name="content_ass_chunk_i_cd1f73_idx"
                    ),
                    models.Index(
                        fields=["asset_type"], name="content_ass_asset_t_12eac7_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="content_chu_documen_7cdb1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["source_type"], name="content_chu_source__227470_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["chapter_name"], name="content_chu_chapter_f6e8fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["quality_flag"], name="content_chu_quality_730111_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chunk",
            unique_together={("document", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(fields=["status"], name="content_ing_status_90d920_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(
                fields=["document"], name="content_ing_documen_397ffb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(
                fields=["created_at"], name="content_ing_created_8334d9_idx"
            ),
        ),
    ]
