# Generated by Django 5.2.11 on 2026-04-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunk",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("ncert", "NCERT"),
                    ("standard_book", "Standard Book"),
                    ("static", "Static Notes"),
                    ("dynamic", "Current Affairs/Dynamic"),
                ],
                help_text="Matches parent document's source_type for efficient filtering",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("ncert", "NCERT"),
                    ("standard_book", "Standard Book"),
                    ("static", "Static Notes"),
                    ("dynamic", "Current Affairs/Dynamic"),
                ],
                help_text="Content category for retrieval strategy",
                max_length=50,
            ),
        ),
    ]
