# Generated by Django 5.2.12 on 2026-08-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_search_trigram_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embedding",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("book_chunk", "Static book chunk"),
                    ("book_article", "Static book article summary"),
                    ("ca_chunk", "Current-affairs chunk"),
                    ("daily_ca_article", "Daily CA article"),
                    ("topic", "Knowledge topic"),
                ],
                help_text="Type of content being embedded",
                max_length=50,
            ),
        ),
    ]
