services:
  postgres:
    image: postgres:16-alpine
    container_name: TheKnowledgeOrbits_postgres
    environment:
      POSTGRES_DB: TheKnowledgeOrbits
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: TheKnowledgeOrbits_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: TheKnowledgeOrbits_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - backend/.env
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: TheKnowledgeOrbits_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:


networks:
  app_network:
    driver: bridge
