/**
 * Article reader with beautiful typography
 */

'use client';

import { Article } from '@/lib/types';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Clock, FileText, Star, Calendar } from 'lucide-react';
import { formatDate, getQualityColor } from '@/lib/utils';

interface ArticleReaderProps {
    article: Article;
}

export default function ArticleReader({ article }: ArticleReaderProps) {
    return (
        <article className="max-w-4xl mx-auto">
            {/* Header */}
            <header className="mb-8">
                {/* Topic Badge */}
                <div className="mb-4">
                    <Badge variant="secondary" className="text-sm">
                        {article.topic.subject_name} • {article.topic.name}
                    </Badge>
                </div>

                {/* Title */}
                <h1 className="text-4xl md:text-5xl font-bold mb-4 leading-tight">
                    {article.title}
                </h1>

                {/* Summary */}
                {article.summary && (
                    <p className="text-xl text-gray-600 leading-relaxed mb-6">
                        {article.summary}
                    </p>
                )}

                {/* Metadata */}
                <div className="flex flex-wrap items-center gap-4 text-sm text-gray-600 mb-6">
                    <div className="flex items-center gap-1">
                        <Calendar className="h-4 w-4" />
                        <span>{formatDate(article.created_at)}</span>
                    </div>

                    <div className="flex items-center gap-1">
                        <FileText className="h-4 w-4" />
                        <span>{article.word_count} words</span>
                    </div>

                    <div className="flex items-center gap-1">
                        <Clock className="h-4 w-4" />
                        <span>{article.read_time} min read</span>
                    </div>

                    <div className="flex items-center gap-1">
                        <Star className={`h-4 w-4 ${getQualityColor(article.quality_score)}`} />
                        <span className={getQualityColor(article.quality_score)}>
                            Quality: {article.quality_score.toFixed(0)}%
                        </span>
                    </div>
                </div>

                <Separator />
            </header>

            {/* Content */}
            <div className="prose prose-lg prose-slate max-w-none">
                {/* Parse content paragraphs */}
                {article.content.split('\n\n').map((paragraph, index) => {
                    // Skip empty paragraphs
                    if (!paragraph.trim()) return null;

                    // Check if it's a heading (starts with #)
                    if (paragraph.startsWith('#')) {
                        const level = paragraph.match(/^#+/)?.[0].length || 1;
                        const text = paragraph.replace(/^#+\s*/, '');

                        if (level === 1) {
                            return <h1 key={index} className="text-3xl font-bold mt-8 mb-4">{text}</h1>;
                        } else if (level === 2) {
                            return <h2 key={index} className="text-2xl font-bold mt-6 mb-3">{text}</h2>;
                        } else {
                            return <h3 key={index} className="text-xl font-bold mt-4 mb-2">{text}</h3>;
                        }
                    }

                    // Regular paragraph
                    return (
                        <p key={index} className="mb-4 leading-relaxed">
                            {paragraph}
                        </p>
                    );
                })}
            </div>

            {/* Footer */}
            <footer className="mt-12 pt-8 border-t">
                <div className="flex items-center justify-between text-sm text-gray-600">
                    <div>
                        <p className="font-medium">Generated by AI</p>
                        <p>Based on {article.source_chunk_count} source materials</p>
                    </div>

                    <Badge variant="outline">
                        {article.generation_type.replace('_', ' ')}
                    </Badge>
                </div>
            </footer>
        </article>
    );
}
