# Generated by Django 5.2.12 on 2026-04-05 14:12

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_content", "0002_bookchunk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookchunk",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                help_text="PostgreSQL tsvector for BM25 full-text search (keyword matching). Populated on save via SearchVector(chunk_text, config='english'). Indexed with GIN for sub-millisecond keyword queries. Part of the Hybrid RAG pipeline: BM25 + semantic vector.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookchunk",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("wiki", "Wikipedia"),
                    ("govt", "Government Source"),
                    ("news", "News Source"),
                    ("ncert_blend", "NCERT + Wiki Blend"),
                    ("mixed", "Multiple Sources"),
                ],
                default="wiki",
                help_text="Origin of the source material used to generate this chunk. Adding new sources (govt, news) requires only a new string value — no migration needed.",
                max_length=30,
            ),
        ),
    ]
