# Generated by Django 5.2.12 on 2026-04-21 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_content", "0003_alter_bookchunk_search_vector_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="topicrelation",
            new_name="topic_rel_cross_subj_idx",
            old_name="topic_rel_cross_subject_idx",
        ),
    ]
