"""
Analytics Engine Models (PKB-Compliant)

Tables (per DATABASE_SCHEMA.md):
- analytics_daily_aggregate
- analytics_insight
"""

import uuid

from django.conf import settings
from django.db import models


class DailyAggregate(models.Model):
    """
    Daily user activity aggregation.

    Schema from DATABASE_SCHEMA.md (lines 285-295):
    - id (UUID)
    - user_id (FK to auth_user)
    - date (DATE)
    - articles_read (INTEGER)
    - quizzes_taken (INTEGER)
    - total_score (FLOAT)
    - time_spent_seconds (INTEGER)
    - created_at
    - UNIQUE(user_id, date)
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier",
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="daily_aggregates",
        help_text="User",
    )

    date = models.DateField(help_text="Aggregation date")

    articles_read = models.IntegerField(
        default=0, help_text="Articles read on this date"
    )

    quizzes_taken = models.IntegerField(
        default=0, help_text="Quizzes taken on this date"
    )

    total_score = models.FloatField(default=0.0, help_text="Sum of quiz scores")

    time_spent_seconds = models.IntegerField(
        default=0, help_text="Total time spent in seconds"
    )

    created_at = models.DateTimeField(
        auto_now_add=True, help_text="Aggregate creation timestamp"
    )

    class Meta:
        db_table = "analytics_daily_aggregate"  # PKB requirement
        unique_together = [["user", "date"]]
        ordering = ["-date"]
        indexes = [
            models.Index(fields=["user"]),
            models.Index(fields=["date"]),
            models.Index(fields=["user", "-date"]),
        ]

    def __str__(self) -> str:
        return f"{self.user.email} - {self.date}"

    @property
    def average_score(self) -> float:
        """Calculate average quiz score for the day."""
        if self.quizzes_taken > 0:
            return self.total_score / self.quizzes_taken
        return 0.0


class Insight(models.Model):
    """
    User insights (generated by analytics).

    Schema from DATABASE_SCHEMA.md (lines 297-304):
    - id (UUID)
    - user_id (FK to auth_user)
    - insight_type ('weak_topic', 'streak_risk', 'improvement')
    - insight_data (JSONB)
    - generated_at
    - expires_at
    """

    INSIGHT_TYPE_CHOICES = [
        ("weak_topic", "Weak Topic Identified"),
        ("streak_risk", "Streak at Risk"),
        ("improvement", "Performance Improvement"),
        ("milestone", "Milestone Achieved"),
        ("recommendation", "Study Recommendation"),
    ]

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier",
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="insights",
        help_text="User",
    )

    insight_type = models.CharField(
        max_length=50, choices=INSIGHT_TYPE_CHOICES, help_text="Type of insight"
    )

    insight_data = models.JSONField(
        default=dict, help_text="Insight details and metadata"
    )

    generated_at = models.DateTimeField(
        auto_now_add=True, help_text="When insight was generated"
    )

    expires_at = models.DateTimeField(
        null=True, blank=True, help_text="When insight becomes stale"
    )

    class Meta:
        db_table = "analytics_insight"  # PKB requirement
        ordering = ["-generated_at"]
        indexes = [
            models.Index(fields=["user"]),
            models.Index(fields=["insight_type"]),
            models.Index(fields=["-generated_at"]),
        ]

    def __str__(self) -> str:
        return f"{self.user.email} - {self.get_insight_type_display()}"

    @property
    def is_expired(self) -> bool:
        """Check if insight has expired."""
        if not self.expires_at:
            return False
        from django.utils import timezone

        return timezone.now() > self.expires_at
