"""
Article Generation Engine Models

Stores generated articles and their source attribution.
Articles are RAG-generated from chunks, never ingested directly.
"""

import uuid
from django.db import models
from django.utils.text import slugify
from django.conf import settings


class Article(models.Model):
    """
    Generated articles from RAG pipeline.
    
    Each article is generated from multiple chunks (static + CA).
    Source attribution tracked via ArticleSourceMap.
    """
    
    GENERATION_TYPE_CHOICES = [
        ('ai_generated', 'AI Generated'),
        ('human_curated', 'Human Curated'),
        ('ai_assisted', 'AI Assisted'),
    ]
    
    REVIEW_STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('pending', 'Pending Review'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ]
    
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier for article"
    )
    
    # Content
    title = models.CharField(
        max_length=500,
        help_text="Article title"
    )
    
    slug = models.SlugField(
        max_length=500,
        unique=True,
        blank=True,
        help_text="URL-friendly slug (auto-generated from title)"
    )
    
    content = models.TextField(
        help_text="Full article content (generated by GROQ)"
    )
    
    summary = models.TextField(
        blank=True,
        help_text="Brief summary (150-200 words)"
    )
    
    # Relations
    topic = models.ForeignKey(
        'knowledge.Topic',
        on_delete=models.CASCADE,
        related_name='articles',
        help_text="Primary topic this article covers"
    )
    
    # Metadata
    word_count = models.IntegerField(
        default=0,
        help_text="Total word count"
    )
    
    read_time = models.IntegerField(
        default=0,
        help_text="Estimated read time in minutes (word_count / 200)"
    )
    
    generation_type = models.CharField(
        max_length=20,
        choices=GENERATION_TYPE_CHOICES,
        default='ai_generated',
        help_text="How this article was created"
    )
    
    quality_score = models.FloatField(
        default=0.0,
        help_text="Quality score 0-100 (from validation checks)"
    )
    
    review_status = models.CharField(
        max_length=20,
        choices=REVIEW_STATUS_CHOICES,
        default='draft',
        help_text="Review/approval status"
    )
    
    # Publishing
    is_published = models.BooleanField(
        default=False,
        help_text="Published and visible to users"
    )
    
    published_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When article was published"
    )
    
    published_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='published_articles',
        help_text="User who published this article"
    )
    
    # Generation metadata
    generation_metadata = models.JSONField(
        default=dict,
        blank=True,
        help_text="GROQ generation params, chunk IDs used, etc."
    )
    
    # Timestamps
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="When article was generated"
    )
    
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="Last modification time"
    )

    # ===== OWNERSHIP FIELDS (PKB EXTENSION) =====
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='created_articles',
        null=True,
        blank=True,
        help_text="User who created this article (NULL = system/admin)"
    )
    
    is_public = models.BooleanField(
        default=True,
        help_text="Is this article publicly visible?"
    )
    # ===== END OWNERSHIP FIELDS =====
    
    class Meta:
        db_table = 'article_article'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['topic']),
            models.Index(fields=['slug']),
            models.Index(fields=['is_published', '-published_at']),
            models.Index(fields=['review_status']),
            models.Index(fields=['-created_at']),
        ]
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'
    
    def __str__(self) -> str:
        return self.title
    
    def save(self, *args, **kwargs):
        """Auto-generate slug if not provided."""
        if not self.slug:
            base_slug = slugify(self.title)
            slug = base_slug
            counter = 1
            
            while Article.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            self.slug = slug
        
        # Calculate read time
        if self.word_count > 0:
            self.read_time = max(1, self.word_count // 200)
        
        super().save(*args, **kwargs)
    
    @property
    def source_chunk_count(self) -> int:
        """Count of chunks used to generate this article."""
        return self.source_chunks.count()
    
    @property
    def static_chunk_count(self) -> int:
        """Count of static chunks used."""
        return self.source_chunks.filter(chunk__source_type='static').count()
    
    @property
    def ca_chunk_count(self) -> int:
        """Count of CA chunks used."""
        return self.source_chunks.filter(chunk__source_type='dynamic').count()
    
    @property
    def is_user_owned(self) -> bool:
        """Check if article is user-owned."""
        return self.created_by is not None

class ArticleSourceMap(models.Model):
    """
    Maps articles to source chunks (source attribution).
    
    Tracks which chunks were used to generate each article.
    Enables "View Sources" feature for transparency.
    """
    
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier"
    )
    
    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
        related_name='source_chunks',
        help_text="Article that was generated"
    )
    
    chunk = models.ForeignKey(
        'content.Chunk',
        on_delete=models.CASCADE,
        related_name='article_usages',
        help_text="Source chunk used in generation"
    )
    
    # Metadata
    relevance_weight = models.FloatField(
        default=1.0,
        help_text="How relevant this chunk was (0.0-1.0)"
    )
    
    sequence_order = models.IntegerField(
        default=0,
        help_text="Order in which chunk was used in generation"
    )
    
    chunk_contribution = models.TextField(
        blank=True,
        help_text="What part of article this chunk contributed to"
    )
    
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="When mapping was created"
    )
    
    class Meta:
        db_table = 'article_sourcemap'
        ordering = ['article', 'sequence_order']
        unique_together = [['article', 'chunk']]
        indexes = [
            models.Index(fields=['article']),
            models.Index(fields=['chunk']),
            models.Index(fields=['article', 'sequence_order']),
        ]
        verbose_name = 'Article Source Map'
        verbose_name_plural = 'Article Source Maps'
    
    def __str__(self) -> str:
        return f"{self.article.title} → Chunk {self.chunk.chunk_index}"


class ArticleGenerationJob(models.Model):
    """
    Tracks article generation jobs (async processing).
    
    Used when generation takes >5 seconds (queued via Celery).
    """
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]
    
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier"
    )
    
    topic = models.ForeignKey(
        'knowledge.Topic',
        on_delete=models.CASCADE,
        related_name='generation_jobs',
        help_text="Topic for which article is being generated"
    )
    
    article = models.ForeignKey(
        Article,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='generation_job',
        help_text="Generated article (null until completed)"
    )
    
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='pending',
        help_text="Current job status"
    )
    
    error_log = models.TextField(
        blank=True,
        help_text="Error details if failed"
    )
    
    # Request params
    requested_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="User who requested generation"
    )
    
    generation_params = models.JSONField(
        default=dict,
        help_text="Generation parameters (include_ca, format, etc.)"
    )
    
    # Timing
    started_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When generation started"
    )
    
    completed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When generation completed"
    )
    
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="When job was queued"
    )
    
    class Meta:
        db_table = 'article_generation_job'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['topic']),
            models.Index(fields=['status']),
            models.Index(fields=['-created_at']),
        ]
        verbose_name = 'Article Generation Job'
        verbose_name_plural = 'Article Generation Jobs'
    
    def __str__(self) -> str:
        return f"Job for {self.topic.name} - {self.status}"

        