# Generated by Django 5.2.12 on 2026-06-10 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query",
                    models.TextField(
                        help_text="Original research question submitted by the user."
                    ),
                ),
                (
                    "query_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 of normalized query for cache lookup.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "langfuse_trace_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Set on failure. Stored for debugging; never shown raw to user.",
                        null=True,
                    ),
                ),
                ("cancelled", models.BooleanField(default=False)),
                ("total_tokens_used", models.IntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ra_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "executive_summary",
                    models.TextField(
                        help_text="300-word summary streamed to user first at ~75s."
                    ),
                ),
                (
                    "full_report",
                    models.TextField(help_text="Complete Markdown research report."),
                ),
                (
                    "sources",
                    models.JSONField(
                        default=list,
                        help_text="List of {url, title, credibility_score} dicts.",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="0.0–1.0 composite score from DeepEval. Null until eval completes.",
                        null=True,
                    ),
                ),
                ("word_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="research_agent.researchsession",
                    ),
                ),
            ],
            options={
                "db_table": "ra_report",
            },
        ),
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hallucination_score",
                    models.FloatField(
                        blank=True,
                        help_text="0.0 (clean) → 1.0 (hallucinated). Lower is better.",
                        null=True,
                    ),
                ),
                (
                    "faithfulness_score",
                    models.FloatField(
                        blank=True,
                        help_text="0.0 → 1.0. Higher = more faithful to sources.",
                        null=True,
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        blank=True,
                        help_text="0.0 → 1.0. Higher = more relevant to the original query.",
                        null=True,
                    ),
                ),
                (
                    "completeness_score",
                    models.FloatField(
                        blank=True,
                        help_text="0.0 → 1.0. Higher = more complete coverage of the query.",
                        null=True,
                    ),
                ),
                (
                    "composite_score",
                    models.FloatField(
                        blank=True,
                        help_text="Weighted composite 0.0–1.0. Written to ra_report.confidence_score.",
                        null=True,
                    ),
                ),
                (
                    "metrics_detail",
                    models.JSONField(
                        default=dict,
                        help_text="Raw DeepEval metric output dicts for developer analysis.",
                    ),
                ),
                ("evaluation_duration_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="research_agent.researchsession",
                    ),
                ),
            ],
            options={
                "db_table": "ra_evaluation",
            },
        ),
        migrations.CreateModel(
            name="AgentStateSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_name",
                    models.CharField(
                        choices=[
                            ("supervisor", "supervisor"),
                            ("planner", "planner"),
                            ("search", "search"),
                            ("research", "research"),
                            ("verification", "verification"),
                            ("summary_generator", "summary_generator"),
                            ("report_generator", "report_generator"),
                            ("reflection", "reflection"),
                        ],
                        max_length=64,
                    ),
                ),
                ("sequence_num", models.SmallIntegerField(default=0)),
                (
                    "state_json",
                    models.JSONField(
                        default=dict,
                        help_text="Full ResearchState dict at this node transition.",
                    ),
                ),
                ("state_size_bytes", models.IntegerField(default=0)),
                ("snapshot_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_snapshots",
                        to="research_agent.researchsession",
                    ),
                ),
            ],
            options={
                "db_table": "ra_state_snapshot",
                "ordering": ["session", "sequence_num"],
            },
        ),
        migrations.CreateModel(
            name="AgentExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        choices=[
                            ("supervisor", "supervisor"),
                            ("planner", "planner"),
                            ("search", "search"),
                            ("research", "research"),
                            ("verification", "verification"),
                            ("summary_generator", "summary_generator"),
                            ("report_generator", "report_generator"),
                            ("reflection", "reflection"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "model_provider",
                    models.CharField(
                        choices=[("groq", "Groq"), ("cerebras", "Cerebras")],
                        max_length=32,
                    ),
                ),
                ("model_name", models.CharField(max_length=64)),
                ("output_summary", models.TextField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("retry_count", models.SmallIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_logs",
                        to="research_agent.researchsession",
                    ),
                ),
            ],
            options={
                "db_table": "ra_agent_log",
                "ordering": ["started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="researchsession",
            index=models.Index(
                fields=["user", "-created_at"], name="ra_session_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchsession",
            index=models.Index(fields=["query_hash"], name="ra_session_query_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="researchsession",
            index=models.Index(fields=["status"], name="ra_session_status_idx"),
        ),
        migrations.AddIndex(
            model_name="agentstatesnapshot",
            index=models.Index(
                fields=["session", "sequence_num"], name="ra_snapshot_session_seq_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentstatesnapshot",
            constraint=models.UniqueConstraint(
                fields=("session", "node_name"), name="ra_snapshot_session_node_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecutionlog",
            index=models.Index(
                fields=["session", "agent_name"], name="ra_agent_log_session_agent_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentexecutionlog",
            constraint=models.UniqueConstraint(
                fields=("session", "agent_name"),
                name="ra_agent_log_session_agent_unique",
            ),
        ),
    ]
