# Generated by Django 5.2.12 on 2026-06-10 17:14

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research_agent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agentstatesnapshot",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["state_json"], name="ra_snapshot_state_json_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["pending", "running", "completed", "failed", "cancelled"],
                    )
                ),
                name="ra_session_status_valid",
            ),
        ),
    ]
