# Generated by Django 5.2.12 on 2026-08-14 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "research_agent",
            "0002_agentstatesnapshot_ra_snapshot_state_json_gin_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("whatsapp", "Whatsapp"), ("email", "Email")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("destination", models.CharField(max_length=254)),
                (
                    "export_format",
                    models.CharField(
                        default="pdf",
                        help_text="'pdf' normally; 'md' when WeasyPrint is unavailable (local dev).",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ra_report_delivery",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_e164", models.CharField(max_length=20, unique=True)),
                ("phone_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp profile name, if Meta sends one. Cosmetic only.",
                        max_length=120,
                        null=True,
                    ),
                ),
                ("opted_in", models.BooleanField(default=True)),
                ("last_inbound_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pending_action",
                    models.CharField(
                        blank=True,
                        choices=[("awaiting_email", "Awaiting email")],
                        help_text="NULL = idle.",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "pending_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="WhatsApp has no 'dismiss' event for an inline button, so a walked-away user is unstuck by this TTL rather than by a close signal.",
                        null=True,
                    ),
                ),
                ("email_retry_count", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ra_wa_contact",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "wa_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Meta's message id. Idempotency key for inbound.",
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("interactive", "Interactive"),
                            ("document", "Document"),
                            ("unsupported", "Unsupported"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Text content, truncated. NULL for documents.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ra_wa_message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="researchsession",
            name="channel",
            field=models.CharField(
                choices=[("web", "Web"), ("whatsapp", "WhatsApp")],
                default="web",
                help_text="Transport the query came from. Existing rows are 'web'.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="researchsession",
            name="channel_ref",
            field=models.CharField(
                blank=True,
                help_text="Hashed external identity. NULL for web sessions.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="researchsession",
            index=models.Index(
                fields=["channel", "-created_at"], name="ra_session_channel_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchsession",
            index=models.Index(
                fields=["channel_ref", "-created_at"], name="ra_session_channel_ref_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel__in", ["web", "whatsapp"])),
                name="ra_session_channel_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("channel", "web"), ("channel_ref__isnull", False), _connector="OR"
                ),
                name="ra_session_channel_ref_required",
            ),
        ),
        migrations.AddField(
            model_name="reportdelivery",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="research_agent.researchsession",
            ),
        ),
        migrations.AddField(
            model_name="whatsappcontact",
            name="pending_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Which report the pending action refers to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="research_agent.researchsession",
            ),
        ),
        migrations.AddField(
            model_name="reportdelivery",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="research_agent.whatsappcontact",
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="research_agent.whatsappcontact",
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_messages",
                to="research_agent.researchsession",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappcontact",
            index=models.Index(fields=["phone_hash"], name="ra_wa_contact_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="whatsappcontact",
            index=models.Index(
                fields=["pending_action"], name="ra_wa_contact_pending_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappcontact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pending_action__isnull", True),
                    ("pending_action__in", ["awaiting_email"]),
                    _connector="OR",
                ),
                name="ra_wa_contact_pending_action_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="reportdelivery",
            index=models.Index(
                fields=["session", "-created_at"], name="ra_delivery_session_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportdelivery",
            index=models.Index(fields=["status"], name="ra_delivery_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="reportdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel__in", ["whatsapp", "email"])),
                name="ra_delivery_channel_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "sent", "failed"])),
                name="ra_delivery_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["contact", "-created_at"], name="ra_wa_msg_contact_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(fields=["session"], name="ra_wa_msg_session_idx"),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(fields=["wa_message_id"], name="ra_wa_msg_waid_idx"),
        ),
        migrations.AddConstraint(
            model_name="whatsappmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction__in", ["inbound", "outbound"])),
                name="ra_wa_message_direction_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["received", "sent", "failed"])),
                name="ra_wa_message_status_valid",
            ),
        ),
    ]
