# Generated by Django 5.2.12 on 2026-08-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research_agent", "0003_whatsapp_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchsession",
            name="channel",
            field=models.CharField(
                choices=[("web", "Web"), ("whatsapp", "WhatsApp")],
                db_default="web",
                default="web",
                help_text="Transport the query came from. Existing rows are 'web'.",
                max_length=20,
            ),
        ),
    ]
