# Generated by Django 5.2.12 on 2026-08-16 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research_agent", "0004_channel_db_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        db_index=True,
                        help_text="A SessionChannel value: telegram, whatsapp, …",
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("external_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Profile name if the platform sends one. Cosmetic only.",
                        max_length=120,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_inbound_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pending_action",
                    models.CharField(
                        blank=True,
                        choices=[("awaiting_email", "Awaiting email")],
                        help_text="NULL = idle.",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "pending_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="No platform emits a 'user dismissed this' event, so a TTL is the only way a walked-away user gets unstuck.",
                        null=True,
                    ),
                ),
                ("email_retry_count", models.SmallIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ra_channel_contact",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChannelMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel", models.CharField(db_index=True, max_length=20)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        help_text="The provider's message id. Idempotency key for inbound.",
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("callback", "Callback"),
                            ("document", "Document"),
                            ("prompt", "Prompt"),
                            ("unsupported", "Unsupported"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Text content, truncated. NULL for documents.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ra_channel_message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="reportdelivery",
            name="ra_delivery_channel_valid",
        ),
        migrations.RemoveConstraint(
            model_name="researchsession",
            name="ra_session_channel_valid",
        ),
        migrations.AlterField(
            model_name="reportdelivery",
            name="channel",
            field=models.CharField(
                choices=[
                    ("whatsapp", "Whatsapp"),
                    ("telegram", "Telegram"),
                    ("email", "Email"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="researchsession",
            name="channel",
            field=models.CharField(
                choices=[
                    ("web", "Web"),
                    ("whatsapp", "Whatsapp"),
                    ("telegram", "Telegram"),
                ],
                db_default="web",
                default="web",
                help_text="Transport the query came from. Existing rows are 'web'.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="researchsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel__in", ["web", "whatsapp", "telegram"])),
                name="ra_session_channel_valid",
            ),
        ),
        migrations.AddField(
            model_name="channelcontact",
            name="pending_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Which report the pending action refers to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="research_agent.researchsession",
            ),
        ),
        migrations.AlterField(
            model_name="reportdelivery",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="research_agent.channelcontact",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel__in", ["whatsapp", "telegram", "email"])),
                name="ra_delivery_channel_valid",
            ),
        ),
        migrations.AddField(
            model_name="channelmessage",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="research_agent.channelcontact",
            ),
        ),
        migrations.AddField(
            model_name="channelmessage",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channel_messages",
                to="research_agent.researchsession",
            ),
        ),
        migrations.AddIndex(
            model_name="channelcontact",
            index=models.Index(fields=["external_hash"], name="ra_ch_contact_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="channelcontact",
            index=models.Index(
                fields=["channel", "pending_action"], name="ra_ch_contact_pending_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="channelcontact",
            constraint=models.UniqueConstraint(
                fields=("channel", "external_id"),
                name="ra_channel_contact_identity_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="channelcontact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pending_action__isnull", True),
                    ("pending_action__in", ["awaiting_email"]),
                    _connector="OR",
                ),
                name="ra_channel_contact_pending_action_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="channelmessage",
            index=models.Index(
                fields=["contact", "-created_at"], name="ra_ch_msg_contact_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelmessage",
            index=models.Index(fields=["session"], name="ra_ch_msg_session_idx"),
        ),
        migrations.AddIndex(
            model_name="channelmessage",
            index=models.Index(
                fields=["provider_message_id"], name="ra_ch_msg_provider_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="channelmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction__in", ["inbound", "outbound"])),
                name="ra_channel_message_direction_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="channelmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["received", "sent", "failed"])),
                name="ra_channel_message_status_valid",
            ),
        ),
    ]
