# Generated by Django 5.2.12 on 2026-09-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research_agent", "0006_widen_model_provider_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("callback", "Callback"),
                    ("command", "Command"),
                    ("document", "Document"),
                    ("prompt", "Prompt"),
                    ("unsupported", "Unsupported"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
