# Generated by Django 5.2.11 on 2026-02-14 12:50

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("current_affairs", "0001_initial"),
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Quiz title (e.g., 'UPSC Polity: Fundamental Rights Quiz')",
                        max_length=500,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        help_text="Overall quiz difficulty",
                        max_length=20,
                    ),
                ),
                (
                    "include_ca",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to include Current Affairs (Hybrid Mode)",
                    ),
                ),
                (
                    "question_count",
                    models.IntegerField(
                        default=10,
                        help_text="Number of questions in quiz",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Time limit in seconds (null = no limit)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is quiz available for attempts?"
                    ),
                ),
                (
                    "generation_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Groq params, chunk IDs used, generation timestamp, etc.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Quiz creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Target topic for this quiz",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="knowledge.topic",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "db_table": "assessment_quiz",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField(help_text="The question stem/text")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_mcq", "Single MCQ"),
                            ("multi_statement", "Multi-Statement"),
                            ("assertion_reasoning", "Assertion-Reasoning"),
                        ],
                        default="single_mcq",
                        help_text="Question format type",
                        max_length=30,
                    ),
                ),
                (
                    "statements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of statements for multi-statement questions",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        help_text="Answer options as JSON object {A: 'text', B: 'text', C: 'text', D: 'text'}"
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        help_text="Correct option key (A, B, C, or D)", max_length=10
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="Detailed explanation with source citations"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        help_text="Question difficulty",
                        max_length=20,
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        default=0, help_text="Display order within quiz"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Question creation timestamp"
                    ),
                ),
                (
                    "source_ca_chunks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="CA chunks used to generate this question",
                        related_name="questions_generated",
                        to="current_affairs.cachunk",
                    ),
                ),
                (
                    "source_static_chunks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Static chunks used to generate this question",
                        related_name="questions_generated",
                        to="content.chunk",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        help_text="Parent quiz",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessment.quiz",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_question",
                "ordering": ["quiz", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("submitted", "Submitted"),
                            ("abandoned", "Abandoned"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        help_text="Current attempt status",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="Score percentage (0-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "correct_count",
                    models.IntegerField(
                        default=0, help_text="Number of correct answers"
                    ),
                ),
                (
                    "wrong_count",
                    models.IntegerField(default=0, help_text="Number of wrong answers"),
                ),
                (
                    "unanswered_count",
                    models.IntegerField(
                        default=0, help_text="Number of unanswered questions"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When quiz was started"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="When quiz was submitted", null=True
                    ),
                ),
                (
                    "time_spent",
                    models.IntegerField(
                        blank=True, help_text="Total time spent in seconds", null=True
                    ),
                ),
                (
                    "attempt_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Browser info, IP (for analytics), question order seen, etc.",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        help_text="Quiz being attempted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessment.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User taking quiz (null for guest mode)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assessment_quiz_attempt",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "selected_option",
                    models.CharField(
                        blank=True,
                        help_text="User's selected answer (A, B, C, D, or empty if unanswered)",
                        max_length=10,
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, help_text="Whether answer is correct"
                    ),
                ),
                (
                    "time_spent",
                    models.IntegerField(
                        default=0, help_text="Time spent on this question in seconds"
                    ),
                ),
                (
                    "marked_for_review",
                    models.BooleanField(
                        default=False, help_text="Whether user marked this for review"
                    ),
                ),
                (
                    "first_visited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user first viewed this question",
                        null=True,
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user answered this question",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Response record creation timestamp",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question being answered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessment.question",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        help_text="Parent quiz attempt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessment.quizattempt",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_question_response",
                "ordering": ["attempt", "question__order_index"],
            },
        ),
        migrations.CreateModel(
            name="TopicMastery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mastery_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Mastery percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "questions_attempted",
                    models.IntegerField(
                        default=0, help_text="Total questions attempted for this topic"
                    ),
                ),
                (
                    "questions_correct",
                    models.IntegerField(
                        default=0, help_text="Total questions answered correctly"
                    ),
                ),
                (
                    "last_attempted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user last attempted a quiz on this topic",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="First attempt timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Topic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_mastery",
                        to="knowledge.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_mastery",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assessment_topic_mastery",
                "ordering": ["-mastery_score"],
            },
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(fields=["topic"], name="assessment__topic_i_655e08_idx"),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["difficulty_level"], name="assessment__difficu_bd5fdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["include_ca"], name="assessment__include_0dce41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["is_active"], name="assessment__is_acti_2c5d32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["-created_at"], name="assessment__created_6ae4c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["quiz", "order_index"], name="assessment__quiz_id_91b1f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_type"], name="assessment__questio_1e0608_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty_level"], name="assessment__difficu_54717f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(fields=["quiz"], name="assessment__quiz_id_14cf2c_idx"),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(fields=["user"], name="assessment__user_id_e19a95_idx"),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(fields=["status"], name="assessment__status_00faf8_idx"),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["-started_at"], name="assessment__started_0b6bfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["quiz", "user"], name="assessment__quiz_id_b0f54f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionresponse",
            index=models.Index(
                fields=["attempt"], name="assessment__attempt_5723aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionresponse",
            index=models.Index(
                fields=["question"], name="assessment__questio_120413_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionresponse",
            index=models.Index(
                fields=["is_correct"], name="assessment__is_corr_c8d2f2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questionresponse",
            unique_together={("attempt", "question")},
        ),
        migrations.AddIndex(
            model_name="topicmastery",
            index=models.Index(
                fields=["user", "-mastery_score"], name="assessment__user_id_2e1ed0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topicmastery",
            index=models.Index(fields=["topic"], name="assessment__topic_i_c76d67_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="topicmastery",
            unique_together={("user", "topic")},
        ),
    ]
