# Generated by Django 5.2.11 on 2026-02-15 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TopicMastery",
        ),
    ]
