# Generated by Django 5.2.11 on 2026-02-16 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0002_add_ownership"),
        ("assessment", "0002_delete_topicmastery"),
    ]

    operations = []
