# Generated by Django 5.2.11 on 2026-02-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_merge_0002_add_ownership_0002_delete_topicmastery"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="quiz",
            name="quiz_created_by_idx",
        ),
        migrations.RemoveIndex(
            model_name="quiz",
            name="quiz_is_public_idx",
        ),
        migrations.RemoveIndex(
            model_name="quiz",
            name="quiz_owner_public_idx",
        ),
    ]
