# Generated by Django 5.2.11 on 2026-03-09 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0006_force_uuid_cast"),
        ("knowledge", "0002_topic_knowledge_t_module__67ee34_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="quiz",
            name="assessment__topic_i_655e08_idx",
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["topic", "-created_at"], name="assessment__topic_i_f1f231_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="assessment__created_b5ae33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["user", "-started_at"], name="assessment__user_id_0fde26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["quiz", "-started_at"], name="assessment__quiz_id_a89b13_idx"
            ),
        ),
    ]
