# Generated by Django 5.2.11 on 2026-02-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        help_text="School, College or Coaching Center",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("aspirant", "UPSC Aspirant"),
                            ("student_school", "School Student"),
                            ("student_college", "College Student"),
                            ("educator", "Educator/Teacher"),
                            ("researcher", "Researcher"),
                            ("other", "Other"),
                        ],
                        default="aspirant",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
