# Generated by Django 5.2.11 on 2026-02-16 08:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(help_text="Aggregation date")),
                (
                    "articles_read",
                    models.IntegerField(
                        default=0, help_text="Articles read on this date"
                    ),
                ),
                (
                    "quizzes_taken",
                    models.IntegerField(
                        default=0, help_text="Quizzes taken on this date"
                    ),
                ),
                (
                    "total_score",
                    models.FloatField(default=0.0, help_text="Sum of quiz scores"),
                ),
                (
                    "time_spent_seconds",
                    models.IntegerField(
                        default=0, help_text="Total time spent in seconds"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Aggregate creation timestamp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_aggregates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_daily_aggregate",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="analytics_d_user_id_2c4354_idx"
                    ),
                    models.Index(fields=["date"], name="analytics_d_date_91aa4b_idx"),
                    models.Index(
                        fields=["user", "-date"], name="analytics_d_user_id_27cd3f_idx"
                    ),
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("weak_topic", "Weak Topic Identified"),
                            ("streak_risk", "Streak at Risk"),
                            ("improvement", "Performance Improvement"),
                            ("milestone", "Milestone Achieved"),
                            ("recommendation", "Study Recommendation"),
                        ],
                        help_text="Type of insight",
                        max_length=50,
                    ),
                ),
                (
                    "insight_data",
                    models.JSONField(
                        default=dict, help_text="Insight details and metadata"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When insight was generated"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When insight becomes stale", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_insight",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="analytics_i_user_id_18bdc7_idx"
                    ),
                    models.Index(
                        fields=["insight_type"], name="analytics_i_insight_ae2bff_idx"
                    ),
                    models.Index(
                        fields=["-generated_at"], name="analytics_i_generat_9158d9_idx"
                    ),
                ],
            },
        ),
    ]
