# Generated by Django 5.0.14 on 2026-02-09 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for article",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Article title", max_length=500)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly slug (auto-generated from title)",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full article content (generated by GROQ)"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Brief summary (150-200 words)"
                    ),
                ),
                (
                    "word_count",
                    models.IntegerField(default=0, help_text="Total word count"),
                ),
                (
                    "read_time",
                    models.IntegerField(
                        default=0,
                        help_text="Estimated read time in minutes (word_count / 200)",
                    ),
                ),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("ai_generated", "AI Generated"),
                            ("human_curated", "Human Curated"),
                            ("ai_assisted", "AI Assisted"),
                        ],
                        default="ai_generated",
                        help_text="How this article was created",
                        max_length=20,
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Quality score 0-100 (from validation checks)",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        help_text="Review/approval status",
                        max_length=20,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Published and visible to users"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="When article was published", null=True
                    ),
                ),
                (
                    "generation_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="GROQ generation params, chunk IDs used, etc.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When article was generated"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification time"
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who published this article",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Primary topic this article covers",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="knowledge.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "db_table": "article_article",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current job status",
                        max_length=20,
                    ),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, help_text="Error details if failed"),
                ),
                (
                    "generation_params",
                    models.JSONField(
                        default=dict,
                        help_text="Generation parameters (include_ca, format, etc.)",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When generation started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When generation completed", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When job was queued"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        help_text="Generated article (null until completed)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_job",
                        to="article_generation.article",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who requested generation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Topic for which article is being generated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="knowledge.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Generation Job",
                "verbose_name_plural": "Article Generation Jobs",
                "db_table": "article_generation_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleSourceMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relevance_weight",
                    models.FloatField(
                        default=1.0, help_text="How relevant this chunk was (0.0-1.0)"
                    ),
                ),
                (
                    "sequence_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which chunk was used in generation",
                    ),
                ),
                (
                    "chunk_contribution",
                    models.TextField(
                        blank=True,
                        help_text="What part of article this chunk contributed to",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When mapping was created"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Article that was generated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_chunks",
                        to="article_generation.article",
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        help_text="Source chunk used in generation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_usages",
                        to="content.chunk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Source Map",
                "verbose_name_plural": "Article Source Maps",
                "db_table": "article_sourcemap",
                "ordering": ["article", "sequence_order"],
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["topic"], name="article_art_topic_i_8b3c45_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="article_art_slug_403059_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_published", "-published_at"],
                name="article_art_is_publ_96afe6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["review_status"], name="article_art_review__8c3262_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-created_at"], name="article_art_created_d3bafd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articlegenerationjob",
            index=models.Index(fields=["topic"], name="article_gen_topic_i_712d82_idx"),
        ),
        migrations.AddIndex(
            model_name="articlegenerationjob",
            index=models.Index(fields=["status"], name="article_gen_status_7ad6b8_idx"),
        ),
        migrations.AddIndex(
            model_name="articlegenerationjob",
            index=models.Index(
                fields=["-created_at"], name="article_gen_created_f0951e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articlesourcemap",
            index=models.Index(
                fields=["article"], name="article_sou_article_9980f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articlesourcemap",
            index=models.Index(fields=["chunk"], name="article_sou_chunk_i_36417b_idx"),
        ),
        migrations.AddIndex(
            model_name="articlesourcemap",
            index=models.Index(
                fields=["article", "sequence_order"],
                name="article_sou_article_3e8ade_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articlesourcemap",
            unique_together={("article", "chunk")},
        ),
    ]
