# Generated by Django 5.2.11 on 2026-02-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article_generation", "0002_add_ownership"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="article_created_by_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="article_is_public_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="article_owner_public_idx",
        ),
    ]
