# Generated by Django 5.2.11 on 2026-03-09 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article_generation", "0004_fix_article_gen_user_uuids"),
        ("knowledge", "0002_topic_knowledge_t_module__67ee34_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="article_art_topic_i_8b3c45_idx",
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["topic", "-created_at"], name="article_art_topic_i_f67fcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="article_art_created_84a6e3_idx",
            ),
        ),
    ]
