# Generated by Django 5.0.14 on 2026-02-10 15:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CAArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Article title", max_length=500)),
                (
                    "url",
                    models.URLField(
                        help_text="Article URL (must be unique)",
                        max_length=1000,
                        unique=True,
                    ),
                ),
                ("content", models.TextField(help_text="Full article content")),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Article summary (if available)",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(help_text="Publication timestamp from source"),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Article author",
                        max_length=200,
                    ),
                ),
                (
                    "categories",
                    models.JSONField(default=list, help_text="Article categories/tags"),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Processing status",
                        max_length=20,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True, default="", help_text="Processing error (if failed)"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing completed", null=True
                    ),
                ),
                (
                    "word_count",
                    models.IntegerField(default=0, help_text="Article word count"),
                ),
                (
                    "chunk_count",
                    models.IntegerField(
                        default=0, help_text="Number of chunks generated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ca_article",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="CAChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chunk_text",
                    models.TextField(help_text="Chunk content (~1200 chars)"),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="Sequential chunk index within article"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        default="dynamic",
                        help_text="Always 'dynamic' for CA chunks",
                        max_length=50,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(help_text="Original article publication date"),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        help_text="When this chunk becomes stale (published_at + 180 days)"
                    ),
                ),
                (
                    "is_expired",
                    models.BooleanField(
                        default=False, help_text="Whether this chunk has expired"
                    ),
                ),
                (
                    "quality_flag",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="medium",
                        help_text="Quality assessment",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=0.7, help_text="Confidence score (0-1)"),
                ),
                (
                    "embedding_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to embedding in content_embedding table",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ca_article",
                    models.ForeignKey(
                        help_text="CA article this chunk belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="current_affairs.caarticle",
                    ),
                ),
            ],
            options={
                "db_table": "ca_chunk",
                "ordering": ["ca_article", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="CASource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Source name (e.g., 'The Hindu')", max_length=200
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        default="rss",
                        help_text="Source type (rss, api, manual)",
                        max_length=50,
                    ),
                ),
                ("url", models.URLField(help_text="RSS feed URL", max_length=500)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether to scrape this source"
                    ),
                ),
                (
                    "scrape_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="daily",
                        help_text="How often to scrape",
                        max_length=20,
                    ),
                ),
                (
                    "last_scraped_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful scrape timestamp",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, default="", help_text="Last scraping error (if any)"
                    ),
                ),
                (
                    "article_count",
                    models.IntegerField(
                        default=0, help_text="Total articles scraped from this source"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ca_source",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="ca_source_is_acti_ad8511_idx"
                    ),
                    models.Index(
                        fields=["last_scraped_at"], name="ca_source_last_sc_b75b85_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="caarticle",
            name="source",
            field=models.ForeignKey(
                help_text="Source this article came from",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="current_affairs.casource",
            ),
        ),
        migrations.CreateModel(
            name="CATopicLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        default=1.0,
                        help_text="How relevant this chunk is to topic (0-1)",
                    ),
                ),
                (
                    "link_method",
                    models.CharField(
                        choices=[
                            ("auto", "Auto-linked (AI)"),
                            ("manual", "Manual (Admin)"),
                        ],
                        default="auto",
                        help_text="How this link was created",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ca_chunk",
                    models.ForeignKey(
                        help_text="CA chunk",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_links",
                        to="current_affairs.cachunk",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Linked topic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ca_links",
                        to="knowledge.topic",
                    ),
                ),
            ],
            options={
                "db_table": "ca_topic_link",
                "ordering": ["-relevance_score"],
            },
        ),
        migrations.AddIndex(
            model_name="cachunk",
            index=models.Index(
                fields=["ca_article", "chunk_index"], name="ca_chunk_ca_arti_54b4eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cachunk",
            index=models.Index(
                fields=["published_at"], name="ca_chunk_publish_bc97ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cachunk",
            index=models.Index(
                fields=["expiry_date"], name="ca_chunk_expiry__ead827_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cachunk",
            index=models.Index(
                fields=["is_expired"], name="ca_chunk_is_expi_e44d0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cachunk",
            index=models.Index(
                fields=["source_type"], name="ca_chunk_source__a33acc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caarticle",
            index=models.Index(
                fields=["source", "published_at"], name="ca_article_source__bbe5f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caarticle",
            index=models.Index(
                fields=["processing_status"], name="ca_article_process_d7b9cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caarticle",
            index=models.Index(
                fields=["published_at"], name="ca_article_publish_f04276_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catopiclink",
            index=models.Index(
                fields=["ca_chunk"], name="ca_topic_li_ca_chun_0a2263_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catopiclink",
            index=models.Index(fields=["topic"], name="ca_topic_li_topic_i_df2942_idx"),
        ),
        migrations.AddIndex(
            model_name="catopiclink",
            index=models.Index(
                fields=["relevance_score"], name="ca_topic_li_relevan_43e4cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="catopiclink",
            unique_together={("ca_chunk", "topic")},
        ),
    ]
