# Generated by Django 5.2.11 on 2026-03-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("current_affairs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="caarticle",
            name="ca_article_source__bbe5f0_idx",
        ),
        migrations.RemoveIndex(
            model_name="caarticle",
            name="ca_article_publish_f04276_idx",
        ),
        migrations.AddIndex(
            model_name="caarticle",
            index=models.Index(
                fields=["source", "-published_at"], name="ca_article_source__42b985_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caarticle",
            index=models.Index(
                fields=["-published_at"], name="ca_article_publish_cdda16_idx"
            ),
        ),
    ]
