# Generated by Django 5.2.11 on 2026-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "current_affairs",
            "0002_remove_caarticle_ca_article_source__bbe5f0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="caarticle",
            index=models.Index(
                fields=["source", "processing_status"],
                name="ca_article_source__547539_idx",
            ),
        ),
    ]
