# Generated by Django 5.0.14 on 2026-02-09 08:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Theme name", max_length=200, unique=True
                    ),
                ),
                ("description", models.TextField(help_text="Theme description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this theme active?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_theme",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Program name (e.g., UPSC CSE)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description"),
                ),
                (
                    "exam_pattern",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Exam structure (prelims, mains, interview)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this program currently active?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_program",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="knowledge_p_name_bf70fe_idx"),
                    models.Index(
                        fields=["is_active"], name="knowledge_p_is_acti_5ab6cf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Subject name", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Subject description"),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        default=0, help_text="Display order within program"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this subject active?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Parent program",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="knowledge.program",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_subject",
                "ordering": ["program", "order_index", "name"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Module name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Module description"),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        default=0, help_text="Display order within subject"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this module active?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Parent subject",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="knowledge.subject",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_module",
                "ordering": ["subject", "order_index", "name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Topic name", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed topic description"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Keywords for AI mapping (list of strings)",
                    ),
                ),
                (
                    "topic_type",
                    models.CharField(
                        choices=[
                            ("syllabus", "Syllabus Topic"),
                            ("custom", "Custom Topic"),
                        ],
                        default="syllabus",
                        help_text="Topic classification",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        help_text="Difficulty level",
                        max_length=20,
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        default=0, help_text="Display order within module"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this topic active?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        help_text="Parent module",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="knowledge.module",
                    ),
                ),
                (
                    "parent_topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent topic (for sub-topics)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="knowledge.topic",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Parent subject (for quick access)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="knowledge.subject",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_topic",
                "ordering": ["module", "order_index", "name"],
            },
        ),
        migrations.CreateModel(
            name="ThemeTopicMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Importance weight for this topic in the theme",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        help_text="Parent theme",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.theme",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Linked topic",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.topic",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_theme_topic_map",
                "ordering": ["-weight"],
            },
        ),
        migrations.AddField(
            model_name="theme",
            name="topics",
            field=models.ManyToManyField(
                help_text="Topics included in this theme",
                related_name="themes",
                through="knowledge.ThemeTopicMap",
                to="knowledge.topic",
            ),
        ),
        migrations.CreateModel(
            name="ChunkTopicMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        default=1.0,
                        help_text="Relevance score (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Priority level (1=basic, 2=intermediate, 3=advanced)",
                    ),
                ),
                (
                    "auto_mapped",
                    models.BooleanField(
                        default=False,
                        help_text="Was this mapping created automatically by AI?",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved this mapping",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        help_text="Source chunk",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_mappings",
                        to="content.chunk",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Target topic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunk_mappings",
                        to="knowledge.topic",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_chunk_topic_map",
                "ordering": ["-relevance_score", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="ChunkRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("duplicate", "Duplicate"),
                            ("similar", "Similar"),
                            ("expands", "Expands On"),
                            ("contradicts", "Contradicts"),
                        ],
                        help_text="Type of relationship",
                        max_length=20,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        help_text="Similarity score (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "chunk_1",
                    models.ForeignKey(
                        help_text="First chunk",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_as_source",
                        to="content.chunk",
                    ),
                ),
                (
                    "chunk_2",
                    models.ForeignKey(
                        help_text="Second chunk",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_as_target",
                        to="content.chunk",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_chunk_relation",
                "indexes": [
                    models.Index(
                        fields=["chunk_1"], name="knowledge_c_chunk_1_5d9f25_idx"
                    ),
                    models.Index(
                        fields=["chunk_2"], name="knowledge_c_chunk_2_d98989_idx"
                    ),
                    models.Index(
                        fields=["relation_type"], name="knowledge_c_relatio_b1da57_idx"
                    ),
                ],
                "unique_together": {("chunk_1", "chunk_2")},
            },
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["program", "order_index"], name="knowledge_s_program_119643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["is_active"], name="knowledge_s_is_acti_62eab2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("program", "name")},
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["subject", "order_index"], name="knowledge_m_subject_583daf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["is_active"], name="knowledge_m_is_acti_7b2b27_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="module",
            unique_together={("subject", "name")},
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["module", "order_index"], name="knowledge_t_module__d0a660_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["subject"], name="knowledge_t_subject_646ae8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["parent_topic"], name="knowledge_t_parent__00f086_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["difficulty_level"], name="knowledge_t_difficu_67caac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["topic_type"], name="knowledge_t_topic_t_382ef8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["is_active"], name="knowledge_t_is_acti_9e2bc7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("module", "name")},
        ),
        migrations.AddIndex(
            model_name="themetopicmap",
            index=models.Index(fields=["theme"], name="knowledge_t_theme_i_6b582b_idx"),
        ),
        migrations.AddIndex(
            model_name="themetopicmap",
            index=models.Index(fields=["topic"], name="knowledge_t_topic_i_5b6d1f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="themetopicmap",
            unique_together={("theme", "topic")},
        ),
        migrations.AddIndex(
            model_name="theme",
            index=models.Index(fields=["name"], name="knowledge_t_name_6624be_idx"),
        ),
        migrations.AddIndex(
            model_name="theme",
            index=models.Index(
                fields=["is_active"], name="knowledge_t_is_acti_64ed41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chunktopicmap",
            index=models.Index(fields=["chunk"], name="knowledge_c_chunk_i_d73960_idx"),
        ),
        migrations.AddIndex(
            model_name="chunktopicmap",
            index=models.Index(fields=["topic"], name="knowledge_c_topic_i_48dad6_idx"),
        ),
        migrations.AddIndex(
            model_name="chunktopicmap",
            index=models.Index(
                fields=["topic", "-relevance_score"],
                name="knowledge_c_topic_i_2b4e2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chunktopicmap",
            index=models.Index(
                fields=["auto_mapped"], name="knowledge_c_auto_ma_9e81e8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chunktopicmap",
            unique_together={("chunk", "topic")},
        ),
    ]
