# Generated by Django 5.2.11 on 2026-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["module", "is_active"], name="knowledge_t_module__67ee34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["subject", "is_active"], name="knowledge_t_subject_bd7b59_idx"
            ),
        ),
    ]
