# Generated by Django 5.2.12 on 2026-04-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0002_topic_knowledge_t_module__67ee34_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("subject_root", "Subject Root"),
                    ("module", "Module"),
                    ("topic", "Topic"),
                    ("subtopic", "Subtopic"),
                    ("sub_subtopic", "Sub-Subtopic"),
                ],
                default="topic",
                help_text="Hierarchy depth: subject_root → module → topic → subtopic → sub_subtopic. Drives graph node visual type and hamburger navbar depth.",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["node_type"], name="knowledge_t_node_ty_770636_idx"
            ),
        ),
    ]
