# Generated by Django 5.2.12 on 2026-04-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0003_topic_add_node_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="content_status",
            field=models.CharField(
                default="empty",
                help_text="Generation status of this node's book content. Values: empty | generating | book_quality | failed",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["content_status"], name="knowledge_t_content_9d9c3f_idx"
            ),
        ),
    ]
