# Generated by Django 5.2.12 on 2026-09-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0005_search_trigram_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL slug from `name`, set once at creation and never rewritten",
                max_length=230,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL slug from `name`, set once at creation and never rewritten",
                max_length=230,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL slug from `name`, set once at creation and never rewritten",
                max_length=230,
                null=True,
                unique=True,
            ),
        ),
    ]
