# Generated by Django 5.2.11 on 2026-02-15 11:14

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_articles_read",
                    models.IntegerField(default=0, help_text="Total articles read"),
                ),
                (
                    "total_quizzes_taken",
                    models.IntegerField(default=0, help_text="Total quizzes taken"),
                ),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0, help_text="Current consecutive days active"
                    ),
                ),
                (
                    "syllabus_coverage_percent",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of syllabus covered",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "userstate_progress",
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("quiz", "Quiz"),
                            ("chunk", "Chunk"),
                        ],
                        help_text="Type of content bookmarked",
                        max_length=50,
                    ),
                ),
                (
                    "content_id",
                    models.UUIDField(help_text="UUID of bookmarked content"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal notes (extension to PKB)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Bookmark creation timestamp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who bookmarked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "userstate_bookmark",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="userstate_b_user_id_85ef05_idx"
                    ),
                    models.Index(
                        fields=["content_type"], name="userstate_b_content_439ea2_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="userstate_b_created_243a95_idx"
                    ),
                ],
                "unique_together": {("user", "content_type", "content_id")},
            },
        ),
        migrations.CreateModel(
            name="ReadingProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "article_id",
                    models.UUIDField(
                        help_text="Article UUID (from article_generation engine)"
                    ),
                ),
                (
                    "percent_read",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of article read",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "last_position",
                    models.IntegerField(
                        default=0, help_text="Last scroll position or paragraph index"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "userstate_reading_progress",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="userstate_r_user_id_f57b87_idx"
                    ),
                    models.Index(
                        fields=["article_id"], name="userstate_r_article_5b3c95_idx"
                    ),
                ],
                "unique_together": {("user", "article_id")},
            },
        ),
        migrations.CreateModel(
            name="TopicMastery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mastery_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Mastery percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "questions_attempted",
                    models.IntegerField(
                        default=0, help_text="Total questions attempted for this topic"
                    ),
                ),
                (
                    "questions_correct",
                    models.IntegerField(
                        default=0, help_text="Total questions answered correctly"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Topic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_masteries",
                        to="knowledge.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_masteries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "userstate_topic_mastery",
                "ordering": ["-mastery_score"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="userstate_t_user_id_bc119c_idx"
                    ),
                    models.Index(
                        fields=["topic"], name="userstate_t_topic_i_8cdf69_idx"
                    ),
                    models.Index(
                        fields=["user", "-mastery_score"],
                        name="userstate_t_user_id_1cbdfa_idx",
                    ),
                ],
                "unique_together": {("user", "topic")},
            },
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("article_read", "Article Read"),
                            ("article_generated", "Article Generated"),
                            ("quiz_started", "Quiz Started"),
                            ("quiz_completed", "Quiz Completed"),
                            ("bookmark_added", "Bookmark Added"),
                            ("bookmark_removed", "Bookmark Removed"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        help_text="Type of event",
                        max_length=50,
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(
                        default=dict, help_text="Additional event metadata"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Event timestamp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "userstate_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="userstate_e_user_id_ebed7b_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="userstate_e_event_t_8316b3_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="userstate_e_created_8b007a_idx"
                    ),
                ],
            },
        ),
    ]
