# Generated by Django 5.2.12 on 2026-04-29 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userstate", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("article_read", "Article Read"),
                    ("article_generated", "Article Generated"),
                    ("daily_ca_article_read", "Daily CA Article Read"),
                    ("quiz_started", "Quiz Started"),
                    ("quiz_completed", "Quiz Completed"),
                    ("bookmark_added", "Bookmark Added"),
                    ("bookmark_removed", "Bookmark Removed"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                ],
                help_text="Type of event",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Cloudinary secure URL for avatar image",
                        max_length=500,
                    ),
                ),
                (
                    "avatar_public_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cloudinary public_id — required for deletion",
                        max_length=255,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short user bio",
                        max_length=500,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Owning user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "userstate_profile",
                "ordering": ["user"],
            },
        ),
    ]
