# Generated by Django 5.2.12 on 2026-04-29 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userstate", "0002_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_weekly_report",
                    models.BooleanField(
                        default=True, help_text="Weekly learning summary email"
                    ),
                ),
                (
                    "email_orbit_alerts",
                    models.BooleanField(
                        default=False, help_text="New articles for saved topics"
                    ),
                ),
                (
                    "email_comment_replies",
                    models.BooleanField(
                        default=True,
                        help_text="Email when someone replies to a comment",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Owning user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "userstate_preferences",
                "ordering": ["user"],
            },
        ),
    ]
