"""
engines/research_agent/graph/state.py
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ResearchState — the single shared baton passed between all 7 LangGraph nodes.

RULES (enforced here, not negotiable):
  1. Every field MUST be JSON-serializable — no ORM models, no datetime objects.
  2. Optional fields default to None / [] / {} — never left undefined.
  3. 'cancelled' MUST be checked by every agent before doing any work.
  4. 'total_tokens_used' MUST be incremented after every LLM call.

Flow:
  Supervisor → Planner → Search → Research →
  Verification → [retry?] → SummaryGenerator →
  ReportGenerator → Reflection → END
"""

from __future__ import annotations

import operator
from typing import Annotated, Optional
from typing_extensions import TypedDict


class ResearchState(TypedDict):
    """
    Shared state flowing through all LangGraph nodes.

    Annotated[list, operator.add] means: when two nodes both write
    to this field, their lists get MERGED (not overwritten).
    Used for fields that accumulate across retry loops.
    """

    # ── Identity ──────────────────────────────────────────────────────────────
    session_id: str
    # UUID of ResearchSession DB row. Set once by Supervisor. Never changes.

    query: str
    # The original user research question. Never modified after Supervisor sets it.

    user_id: Optional[str]
    # auth_user UUID as string (nullable — anonymous users have None).
    # FK to auth_user table. NEVER import auth models here — just store the UUID.

    langfuse_trace_id: Optional[str]
    # Set by Supervisor after opening Langfuse trace. Used by all agents
    # to attach their spans to the correct parent trace.

    # ── Planner output ────────────────────────────────────────────────────────
    research_plan: Optional[str]
    # Full research plan text generated by Planner agent.
    # Guides all downstream agents on what to focus on.

    sub_queries: list[str]
    # Max 3 search queries derived from the main query by Planner.
    # Search agent fires all 3 in parallel via Tavily/Exa/Wikipedia.

    domain: Optional[str]
    # Knowledge domain classified by DomainClassifier tool.
    # Examples: 'polity', 'economy', 'geography', 'science', 'current_affairs'
    # Used to tailor search strategy and prompts.

    # ── Search output ─────────────────────────────────────────────────────────
    raw_search_results: Annotated[list[dict], operator.add]
    # Each dict: {url, title, content, source, credibility_score}
    # Annotated with operator.add so retry loops APPEND new results
    # instead of overwriting previous ones.

    sources_used: Annotated[list[str], operator.add]
    # Deduplicated list of URLs actually used in synthesis.
    # Accumulates across retries.

    # ── Research output ───────────────────────────────────────────────────────
    synthesized_content: Optional[str]
    # Research Agent's synthesis of raw_search_results into coherent content.
    # Input to Verification Agent.

    key_findings: list[str]
    # Bullet-point key facts extracted by Research Agent.
    # Used by Verification Agent to fact-check each finding.

    # ── Verification output ───────────────────────────────────────────────────
    verification_passed: bool
    # True = Verification Agent approved the findings.
    # False = triggers retry loop back to Search (max 1 retry).

    verification_notes: Optional[str]
    # Verification Agent's reasoning. Stored in AgentExecutionLog.output_summary.

    retry_count: int
    # How many verification retries have happened. Max = MAX_VERIFICATION_RETRIES (1).
    # Router checks this to prevent infinite loops.

    # ── Summary output (Opt #2: executive summary first) ──────────────────────
    executive_summary: Optional[str]
    # 300-word summary generated by SummaryGenerator BEFORE full report.
    # Streamed to user at ~75s so they have something to read immediately.

    # ── Report output ─────────────────────────────────────────────────────────
    final_report: Optional[str]
    # Full structured Markdown report from ReportGenerator.
    # Streamed token-by-token via SSE report_token events.

    report_word_count: int
    # Word count of final_report. Stored in ResearchReport DB row.

    # ── Reflection output ─────────────────────────────────────────────────────
    reflection_score: float
    # 0.0–1.0. ReflectionAgent self-evaluates report quality.
    # If < 0.7 → one re-plan pass triggered. If >= 0.7 → workflow ends.

    reflection_notes: Optional[str]
    # ReflectionAgent's reasoning for the score.

    # ── Telemetry (LLMOps) ────────────────────────────────────────────────────
    agent_timings: dict[str, float]
    # {agent_name: duration_ms} — populated by each agent after completing.
    # Saved to AgentExecutionLog. Visible in Langfuse trace timeline.

    tokens_per_agent: dict[str, int]
    # {agent_name: tokens_used} — populated by each agent after LLM call.
    # Feeds into total_tokens_used and per-agent Langfuse span metadata.

    errors: Annotated[list[str], operator.add]
    # Non-fatal error messages collected across all agents.
    # Annotated with operator.add so errors accumulate (not overwrite).
    # Fatal errors raise exceptions; non-fatal ones land here.

    # ── Production Safety ─────────────────────────────────────────────────────
    cancelled: bool
    # Set to True when user disconnects or hits Cancel button.
    # EVERY agent checks this as the FIRST line of its run() method.
    # If True → agent returns state unchanged immediately (no LLM call).

    total_tokens_used: int
    # Running total of tokens across ALL agents in this session.
    # Incremented after every LLM call. Used for abuse detection (Risk #40).
    # Saved to ResearchSession DB row on completion.


def make_initial_state(
    session_id: str,
    query: str,
    user_id: Optional[str] = None,
) -> ResearchState:
    """
    Factory function — creates a clean ResearchState for a new session.
    Called by the Orchestrator before invoking the compiled LangGraph.

    Every field is explicitly initialized here.
    LangGraph requires ALL TypedDict keys to be present at graph entry.
    """
    return ResearchState(
        # Identity
        session_id=session_id,
        query=query,
        user_id=user_id,
        langfuse_trace_id=None,
        # Planner
        research_plan=None,
        sub_queries=[],
        domain=None,
        # Search
        raw_search_results=[],
        sources_used=[],
        # Research
        synthesized_content=None,
        key_findings=[],
        # Verification
        verification_passed=False,
        verification_notes=None,
        retry_count=0,
        # Summary + Report
        executive_summary=None,
        final_report=None,
        report_word_count=0,
        # Reflection
        reflection_score=0.0,
        reflection_notes=None,
        # Telemetry
        agent_timings={},
        tokens_per_agent={},
        errors=[],
        # Production Safety
        cancelled=False,
        total_tokens_used=0,
    )
