# Generated by Django 5.2.12 on 2026-04-10 07:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0004_topic_add_content_status_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaDailyProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="The news date this proposal is based on (usually today or yesterday)",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="10–15 word article title generated by GROQ",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="3-sentence news summary for human reviewer in Django admin"
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(
                        blank=True,
                        help_text="UPSC subject name derived from the linked topic",
                        max_length=200,
                    ),
                ),
                (
                    "gs_paper",
                    models.CharField(
                        blank=True,
                        help_text="GS paper classification: GS1 / GS2 / GS3 / GS4",
                        max_length=10,
                    ),
                ),
                (
                    "source_urls",
                    models.JSONField(
                        default=list,
                        help_text="List of source dicts: [{source_name, url, title}]",
                    ),
                ),
                (
                    "ca_chunk_ids",
                    models.JSONField(
                        default=list,
                        help_text="UUIDs of top 3 CAArticle chunks used to build this proposal",
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.0,
                        help_text="UPSC relevance score 0–10 from RelevanceScorerService",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("generated", "Article Generated"),
                            ("failed", "Generation Failed"),
                            ("queued_next_run", "Queued for Next Run"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when a human approved this proposal",
                        null=True,
                    ),
                ),
                (
                    "generated_article_id",
                    models.UUIDField(
                        blank=True,
                        help_text="PK of the DailyCaArticle generated from this proposal (FK constraint to daily_ca.DailyCaArticle added in Phase J)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked UPSC syllabus topic from the knowledge engine",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ca_proposals",
                        to="knowledge.topic",
                    ),
                ),
            ],
            options={
                "db_table": "daily_ca_proposal",
                "ordering": ["-relevance_score"],
                "indexes": [
                    models.Index(
                        fields=["date", "status"], name="daily_ca_pr_date_826193_idx"
                    ),
                    models.Index(
                        fields=["-relevance_score"],
                        name="daily_ca_pr_relevan_2e0570_idx",
                    ),
                    models.Index(
                        fields=["status"], name="daily_ca_pr_status_41849a_idx"
                    ),
                ],
                "unique_together": {("date", "topic")},
            },
        ),
    ]
