# Generated by Django 5.2.12 on 2026-04-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_content", "0003_alter_bookchunk_search_vector_and_more"),
        ("daily_ca", "0002_daily_ca_article_static_link"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dailycaarticle",
            new_name="daily_ca_ar_publish_6112ac_idx",
            old_name="daily_ca_art_pub_date_desc_idx",
        ),
        migrations.RenameIndex(
            model_name="dailycaarticle",
            new_name="daily_ca_ar_publish_ebde49_idx",
            old_name="daily_ca_art_pub_ispub_idx",
        ),
        migrations.RenameIndex(
            model_name="dailycaarticle",
            new_name="daily_ca_ar_slug_113ab3_idx",
            old_name="daily_ca_art_slug_idx",
        ),
        migrations.RenameIndex(
            model_name="dailycaarticle",
            new_name="daily_ca_ar_topic_i_4c8d05_idx",
            old_name="daily_ca_art_topic_idx",
        ),
        migrations.RenameIndex(
            model_name="dailycastaticlink",
            new_name="daily_ca_st_daily_a_8f1119_idx",
            old_name="daily_ca_sl_article_idx",
        ),
        migrations.RenameIndex(
            model_name="dailycastaticlink",
            new_name="daily_ca_st_book_co_1c029f_idx",
            old_name="daily_ca_sl_bookcontent_idx",
        ),
        migrations.RemoveField(
            model_name="cadailyproposal",
            name="generated_article_id",
        ),
        migrations.AddField(
            model_name="cadailyproposal",
            name="generated_article",
            field=models.ForeignKey(
                blank=True,
                db_column="generated_article_id",
                help_text="DailyCaArticle generated from this proposal",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposals",
                to="daily_ca.dailycaarticle",
            ),
        ),
        migrations.AlterField(
            model_name="dailycaarticle",
            name="ca_chunk_ids",
            field=models.JSONField(
                default=list,
                help_text="UUIDs of the top-3 CAChunks used as source for generation (audit trail)",
            ),
        ),
        migrations.AlterField(
            model_name="dailycaarticle",
            name="generation_metadata",
            field=models.JSONField(
                default=dict,
                help_text="Audit dict: groq_model, word_count, had_static_anchor, subject, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="dailycaarticle",
            name="hero_image_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cloudinary URL for hero image (blank until Phase M image pipeline)",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="dailycaarticle",
            name="news_context",
            field=models.TextField(
                blank=True,
                default="",
                help_text="3-sentence summary of the news that triggered this article (from proposal.description)",
            ),
        ),
        migrations.AlterField(
            model_name="dailycaarticle",
            name="order_on_date",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Display order within a date (1–10). Set by admin at publish time.",
            ),
        ),
        migrations.AlterField(
            model_name="dailycaarticle",
            name="sources_used",
            field=models.JSONField(
                default=list,
                help_text="List of [{source_name, url, title}] dicts from source CA articles",
            ),
        ),
        migrations.AlterField(
            model_name="dailycaarticle",
            name="static_background",
            field=models.ForeignKey(
                blank=True,
                help_text="BookContent used as factual anchor during generation (null if none existed)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ca_articles",
                to="book_content.bookcontent",
            ),
        ),
    ]
