# Generated by Django 5.2.12 on 2026-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_content", "0003_alter_bookchunk_search_vector_and_more"),
        (
            "daily_ca",
            "0003_rename_daily_ca_art_pub_date_desc_idx_daily_ca_ar_publish_6112ac_idx_and_more",
        ),
        ("knowledge", "0004_topic_add_content_status_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycaarticle",
            name="news_category",
            field=models.CharField(
                choices=[
                    ("national", "National"),
                    ("international", "International"),
                    ("geo-politics", "Geo-Politics"),
                    ("geo-economics", "Geo-Economics"),
                    ("economy", "Economy & Business"),
                    ("science-tech", "Science & Technology"),
                    ("environment", "Environment & Climate"),
                    ("society", "Society & Culture"),
                    ("law-justice", "Law & Justice"),
                    ("defence", "Defence & Security"),
                    ("health", "Health"),
                    ("sports-awards", "Sports & Awards"),
                ],
                db_index=True,
                default="national",
                help_text="Fixed news category — classified by LLM at generation time.",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="dailycaarticle",
            index=models.Index(
                fields=["news_category"], name="daily_ca_ar_news_ca_832c5d_idx"
            ),
        ),
    ]
