# Generated by Django 5.2.12 on 2026-04-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_content", "0004_p14_compound_indexes"),
        ("daily_ca", "0004_add_news_category"),
        ("knowledge", "0004_topic_add_content_status_squashed"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dailycaarticle",
            index=models.Index(
                fields=["published_date", "order_on_date"],
                name="daily_ca_date_order_idx",
            ),
        ),
    ]
