# Generated by Django 5.2.12 on 2026-04-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="comment",
            new_name="social_comm_content_a5309e_idx",
            old_name="social_comment_ct_cid_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="social_comm_parent__aa1e47_idx",
            old_name="social_comment_parent_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="social_comm_user_id_32ff9a_idx",
            old_name="social_comment_user_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="social_comm_is_dele_c9ce22_idx",
            old_name="social_comment_mod_idx",
        ),
        migrations.RenameIndex(
            model_name="like",
            new_name="social_like_content_a8ca87_idx",
            old_name="social_like_ct_cid_idx",
        ),
        migrations.RenameIndex(
            model_name="like",
            new_name="social_like_user_id_867a88_idx",
            old_name="social_like_user_ct_idx",
        ),
        migrations.RenameIndex(
            model_name="share",
            new_name="social_shar_content_c32612_idx",
            old_name="social_share_ct_cid_idx",
        ),
        migrations.RenameIndex(
            model_name="share",
            new_name="social_shar_user_id_12d1ff_idx",
            old_name="social_share_user_idx",
        ),
        migrations.RenameIndex(
            model_name="socialcount",
            new_name="social_coun_content_e51747_idx",
            old_name="social_count_ct_cid_idx",
        ),
        migrations.AlterField(
            model_name="socialcount",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
