# Generated by Django 5.2.12 on 2026-04-10 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConceptPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the concept (e.g. 'Civil Liability for Nuclear Damage Act')",
                        max_length=300,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe slug — auto-set at creation, never changed",
                        max_length=350,
                        unique=True,
                    ),
                ),
                (
                    "brief_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="2-3 line LLM-generated description, created at stub creation time",
                    ),
                ),
                (
                    "body_md",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full markdown content — empty until concept page generation phase runs",
                    ),
                ),
                (
                    "is_content_ready",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="False = stub only (brief_description only). True = full page live.",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of CA articles this concept has been linked from",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "concept_page",
                "ordering": ["-usage_count", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="concept_pag_slug_acfaa4_idx"),
                    models.Index(
                        fields=["-usage_count"], name="concept_pag_usage_c_3db935_idx"
                    ),
                    models.Index(
                        fields=["is_content_ready"],
                        name="concept_pag_is_cont_1e7bb1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Lowercase-hyphenated tag name (e.g. 'nuclear-energy')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe slug — auto-set from name, never changed after creation",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="1-2 sentence explanation of what this tag covers",
                    ),
                ),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("topic", "UPSC Topic"),
                            ("subtopic", "Subtopic"),
                            ("scheme", "Government Scheme"),
                            ("person", "Person/Figure"),
                            ("place", "Place/Geography"),
                            ("organisation", "Organisation/Body"),
                            ("concept", "Concept/Term"),
                            ("law", "Law/Act/Treaty"),
                            ("event", "Event"),
                            ("other", "Other"),
                        ],
                        default="concept",
                        help_text="Classification of this tag for filtering and discovery",
                        max_length=20,
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of articles carrying this tag — updated on every tag/untag",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive tags are hidden from UI but never deleted",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tag",
                "ordering": ["-usage_count", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="tag_slug_0f9213_idx"),
                    models.Index(fields=["tag_type"], name="tag_tag_typ_868e6f_idx"),
                    models.Index(
                        fields=["-usage_count"], name="tag_usage_c_66d176_idx"
                    ),
                    models.Index(fields=["is_active"], name="tag_is_acti_a32dfc_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConceptArticleLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "daily_ca_article_id",
                    models.UUIDField(
                        help_text="PK of the DailyCaArticle this concept is linked from (FK constraint to daily_ca.DailyCaArticle added in Phase E)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concept_page",
                    models.ForeignKey(
                        help_text="The concept page being linked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_links",
                        to="tags.conceptpage",
                    ),
                ),
            ],
            options={
                "db_table": "concept_article_link",
                "indexes": [
                    models.Index(
                        fields=["concept_page"], name="concept_art_concept_15db9d_idx"
                    ),
                    models.Index(
                        fields=["daily_ca_article_id"],
                        name="concept_art_daily_c_71e14b_idx",
                    ),
                ],
                "unique_together": {("concept_page", "daily_ca_article_id")},
            },
        ),
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("daily_ca", "Daily CA Article"),
                            ("book_content", "Static Book Content"),
                        ],
                        help_text="Which article type this tag is applied to",
                        max_length=20,
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        help_text="PK of the linked article (DailyCaArticle or BookContent)"
                    ),
                ),
                (
                    "relevance",
                    models.FloatField(
                        default=1.0,
                        help_text="Tag relevance score 0.0–1.0 (1.0 = primary, <1.0 = secondary)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="The tag being applied",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_tags",
                        to="tags.tag",
                    ),
                ),
            ],
            options={
                "db_table": "article_tag",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="article_tag_content_23a24c_idx",
                    ),
                    models.Index(
                        fields=["tag", "content_type"],
                        name="article_tag_tag_id_1ea70c_idx",
                    ),
                    models.Index(
                        fields=["object_id"], name="article_tag_object__ca502d_idx"
                    ),
                ],
                "unique_together": {("tag", "content_type", "object_id")},
            },
        ),
    ]
