# Generated by Django 5.2.12 on 2026-04-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_conceptarticlelink_fk_daily_ca_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conceptarticlelink",
            name="daily_ca_article_id",
            field=models.UUIDField(
                help_text="PK of the DailyCaArticle this concept is linked from (FK constraint to daily_ca.DailyCaArticle added in Phase E)"
            ),
        ),
    ]
