# Generated by Django 5.2.12 on 2026-04-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0004_add_book_content_concept_link"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="articletag",
            index=models.Index(
                fields=["content_type", "object_id", "relevance"],
                name="article_tag_relevance_idx",
            ),
        ),
    ]
