"""
engines/daily_ca/models.py
━━━━━━━━━━━━━━━━━━━━━━━━━━
Daily CA Engine — Models.

Models defined here (by phase):
  Phase F1 → CaDailyProposal   (proposal queue — human review before generation)
  Phase J1 → DailyCaArticle    (generated article)
  Phase J2 → DailyCaStaticLink (book_content ↔ DailyCaArticle link)
"""

import uuid

from django.db import models


# ── Choices ───────────────────────────────────────────────────────────────────

NEWS_CATEGORY_CHOICES = [
    ("national", "National"),
    ("international", "International"),
    ("geo-politics", "Geo-Politics"),
    ("geo-economics", "Geo-Economics"),
    ("economy", "Economy & Business"),
    ("science-tech", "Science & Technology"),
    ("environment", "Environment & Climate"),
    ("society", "Society & Culture"),
    ("law-justice", "Law & Justice"),
    ("defence", "Defence & Security"),
    ("health", "Health"),
    ("sports-awards", "Sports & Awards"),
]

# ── MODEL: CaDailyProposal ────────────────────────────────────────────────────

PROPOSAL_STATUS_CHOICES = [
    ("pending", "Pending Review"),
    ("approved", "Approved"),
    ("rejected", "Rejected"),
    ("generated", "Article Generated"),
    ("failed", "Generation Failed"),
    ("queued_next_run", "Queued for Next Run"),
    ("duplicate", "Duplicate — skipped by title-overlap dedup"),  # Phase D
]


class CaDailyProposal(models.Model):
    """
    One proposed Daily CA article topic surfaced from yesterday's news.

    Lifecycle:
      pending       → human reviews in Django admin
      approved      → picked up by generate_daily_ca command (Phase J)
      rejected      → skipped permanently
      generated     → DailyCaArticle created; generated_article_id populated
      failed        → generation cycle crashed; can be re-approved and retried
      queued_next_run → session cap hit mid-run; auto-approved for next run

    Deduplication rule: one proposal per (date, topic) — unique_together enforced.
    Three sources on same topic = 1 proposal (not 3), enforced in generate_ca_proposals.

    Fields:
      ca_chunk_ids   — UUIDs of top 3 CAArticle chunks used to build this proposal
      source_urls    — [{source_name, url, title}] for citation display
      relevance_score — 0–10 from RelevanceScorerService; proposals sorted by this
      gs_paper       — "GS1" / "GS2" / "GS3" / "GS4" — LLM-assigned in generation
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    date = models.DateField(
        db_index=True,
        help_text="The news date this proposal is based on (usually today or yesterday)",
    )
    title = models.CharField(
        max_length=500,
        help_text="10–15 word article title generated by GROQ",
    )
    description = models.TextField(
        help_text="3-sentence news summary for human reviewer in Django admin",
    )
    topic = models.ForeignKey(
        "knowledge.Topic",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="ca_proposals",
        help_text="Linked UPSC syllabus topic from the knowledge engine",
    )
    subject_name = models.CharField(
        max_length=200,
        blank=True,
        help_text="UPSC subject name derived from the linked topic",
    )
    gs_paper = models.CharField(
        max_length=10,
        blank=True,
        help_text="GS paper classification: GS1 / GS2 / GS3 / GS4",
    )
    source_urls = models.JSONField(
        default=list,
        help_text="List of source dicts: [{source_name, url, title}]",
    )
    ca_chunk_ids = models.JSONField(
        default=list,
        help_text="UUIDs of top 3 CAArticle chunks used to build this proposal",
    )
    relevance_score = models.FloatField(
        default=0.0,
        help_text="UPSC relevance score 0–10 from RelevanceScorerService",
    )
    status = models.CharField(
        max_length=20,
        choices=PROPOSAL_STATUS_CHOICES,
        default="pending",
        db_index=True,
    )
    approved_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Timestamp when a human approved this proposal",
    )

    # Phase J migration converted this from UUIDField to ForeignKey (SET_NULL).
    generated_article = models.ForeignKey(
        "DailyCaArticle",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="proposals",
        db_column="generated_article_id",
        help_text="DailyCaArticle generated from this proposal",
    )

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "daily_ca_proposal"
        ordering = ["-relevance_score"]
        unique_together = [["date", "topic"]]
        indexes = [
            models.Index(fields=["date", "status"]),
            models.Index(fields=["-relevance_score"]),
            models.Index(fields=["status"]),
        ]

    def __str__(self) -> str:
        return f"[{self.date}] {self.title[:60]} ({self.status})"


# ── MODEL: DailyCaArticle ─────────────────────────────────────────────────────


class DailyCaArticle(models.Model):
    """
    One fully-generated Daily CA article — the core output of the daily pipeline.

    Lifecycle:
      Generator service creates with is_published=False.
      Human admin reviews → sets is_published=True → article goes live.

    body_md            — raw LLM output with [[concept]] brackets (audit trail)
    body_md_processed  — post-processed: [[term]] replaced with [term](/concepts/slug)
    static_background  — FK to BookContent used as factual anchor during generation
                         (null if no published static existed at generation time)
    generation_metadata — audit dict: groq_model, word_count, had_static_anchor, etc.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    title = models.CharField(max_length=500)
    slug = models.SlugField(
        max_length=550,
        unique=True,
        help_text="URL slug: {date}-{title-slug}, e.g. 2026-04-10-india-fast-breeder-reactor",
    )
    topic = models.ForeignKey(
        "knowledge.Topic",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="daily_ca_articles",
        help_text="UPSC syllabus topic this article maps to",
    )
    subject_name = models.CharField(
        max_length=200,
        blank=True,
        help_text="UPSC subject name (denormalised from topic.subject.name)",
    )
    gs_paper = models.CharField(
        max_length=10,
        blank=True,
        help_text="GS paper classification: GS1 / GS2 / GS3 / GS4",
    )
    published_date = models.DateField(
        db_index=True,
        help_text="The calendar date this article is published for",
    )
    body_md = models.TextField(
        help_text="Raw LLM output markdown — preserves [[concept]] brackets for audit",
    )
    body_md_processed = models.TextField(
        default="",
        blank=True,
        help_text="Processed markdown — [[term]] replaced with [term](/concepts/slug) links",
    )
    news_context = models.TextField(
        default="",
        blank=True,
        help_text="3-sentence summary of the news that triggered this article (from proposal.description)",
    )
    sources_used = models.JSONField(
        default=list,
        help_text="List of [{source_name, url, title}] dicts from source CA articles",
    )
    static_background = models.ForeignKey(
        "book_content.BookContent",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="ca_articles",
        help_text="BookContent used as factual anchor during generation (null if none existed)",
    )
    hero_image_url = models.CharField(
        max_length=1000,
        blank=True,
        default="",
        help_text="Cloudinary URL for hero image (blank until Phase M image pipeline)",
    )
    ca_chunk_ids = models.JSONField(
        default=list,
        help_text="UUIDs of the top-3 CAChunks used as source for generation (audit trail)",
    )
    news_category = models.CharField(
        max_length=30,
        choices=NEWS_CATEGORY_CHOICES,
        default="national",
        db_index=True,
        help_text="Fixed news category — classified by LLM at generation time.",
    )
    quality_score = models.FloatField(
        default=0.0,
        help_text="0.0–10.0 quality signal computed post-generation",
    )
    is_published = models.BooleanField(
        default=False,
        db_index=True,
        help_text="False = awaiting admin review. True = live on /daily-ca/",
    )
    generation_metadata = models.JSONField(
        default=dict,
        help_text="Audit dict: groq_model, word_count, had_static_anchor, subject, etc.",
    )
    order_on_date = models.PositiveSmallIntegerField(
        default=0,
        help_text="Display order within a date (1–10). Set by admin at publish time.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "daily_ca_article"
        ordering = ["published_date", "order_on_date"]
        indexes = [
            models.Index(fields=["-published_date"]),
            models.Index(fields=["published_date", "is_published"]),
            models.Index(fields=["slug"]),
            models.Index(fields=["topic"]),
            models.Index(fields=["news_category"]),
            # P1.4 — compound index for TodayView/DateView ORDER BY published_date + order_on_date
            models.Index(
                fields=["published_date", "order_on_date"],
                name="daily_ca_date_order_idx",
            ),
        ]

    def __str__(self) -> str:
        return f"[{self.published_date}] {self.title[:60]}"


# ── MODEL: DailyCaStaticLink ──────────────────────────────────────────────────

LINK_REASON_CHOICES = [
    ("same_topic", "Same Topic"),
    ("background", "Background Context"),
    ("related_concept", "Related Concept"),
]


class DailyCaStaticLink(models.Model):
    """
    Audit record linking a DailyCaArticle to the BookContent used as factual anchor.

    Created in _run_single_cycle() STEP 9 only when:
      - A published BookContent existed for the topic at generation time (Case A)
      - static_background FK is set on DailyCaArticle

    Used for:
      - Frontend "Deep Dive" section below CA article → links to the full static topic article
      - Analytics: which topics have the richest static-CA coverage
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    daily_article = models.ForeignKey(
        DailyCaArticle,
        on_delete=models.CASCADE,
        related_name="static_links",
    )
    book_content = models.ForeignKey(
        "book_content.BookContent",
        on_delete=models.CASCADE,
        related_name="ca_links",
    )
    link_reason = models.CharField(
        max_length=20,
        choices=LINK_REASON_CHOICES,
        default="same_topic",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "daily_ca_static_link"
        unique_together = [["daily_article", "book_content"]]
        indexes = [
            models.Index(fields=["daily_article"]),
            models.Index(fields=["book_content"]),
        ]

    def __str__(self) -> str:
        return f"{self.daily_article.title[:40]} → {self.book_content_id}"
